spring:
  application:
    name:
      task-manager

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/task_manager
    username: postgres
    password: pass

jwt:
  accessTokenExpiration: 900000  #15 минут
  refreshTokenExpiration: 604800000  #7 дней
  secret: snksiwijhwjwouwwwowiwoiwuwuakjwwjauqo